version: "3.8"

services:
  codeql-analyzer:
    platform: linux/amd64
    build: ./tools-scripts/codeql
    volumes:
      - ./target:/root/target
      - ~/.m2:/root/.m2
    working_dir: /root
    entrypoint: ["/root/entrypoint.sh"]
    stdin_open: true
    tty: true
    environment:
      - REPO_NAME=${REPO_NAME}
      - LANGUAGE=${LANGUAGE}

  sonarqube-analyzer:
    platform: linux/amd64
    image: sonarqube:lts
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  
  trufflehog-analyzer:
    build: ./tools-scripts/trufflehog-scan
    volumes:
      - ./target:/root/target
    entrypoint: ["/root/entrypoint.sh"]
    environment:
      - REPO_NAME=${REPO_NAME}
      - LANGUAGE=${LANGUAGE}