version: "3.8"

services:
  codeql-analyzer:
    platform: linux/amd64
    build: ./tools-scripts/codeql
    volumes:
      - ./target:/root/target
      - ~/.m2:/root/.m2
    working_dir: /root
    entrypoint: ["/root/entrypoint.sh"]
    stdin_open: true
    tty: true
    environment:
      - REPO_NAME=${REPO_NAME}
      - LANGUAGE=${LANGUAGE}

  sonarqube-analyzer:
    platform: linux/amd64
    build: ./tools-scripts/sonar/
    volumes:
      - ./target:/root/target
      - ~/.m2:/root/.m2
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - REPO_NAME=${REPO_NAME}
      - LANGUAGE=${LANGUAGE}
    networks:
      - sonar-net
    depends_on:
      - sonarqube  

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: no
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - sonar-net

  trufflehog-analyzer:
    build: ./tools-scripts/trufflehog-scan
    volumes:
      - ./target:/root/target
    entrypoint: ["/root/entrypoint.sh"]
    environment:
      - REPO_NAME=${REPO_NAME}
      - LANGUAGE=${LANGUAGE}  
      
  gitleaks-analyzer:
    platform: "linux/amd64"
    build: ./tools-scripts/gitleaks
    working_dir: /root
    volumes:
      - ./target:/root/target
    entrypoint: ["/root/entrypoint.sh"]
    stdin_open: true
    tty: true
    environment:
      - REPO_NAME=${REPO_NAME}
      - LANGUAGE=${LANGUAGE}
    
  owasp-analyzer:
    platform: linux/amd64
    build: ./tools-scripts/owasp
    working_dir: "/"
    volumes:
      - ./target:/usr/share/dependency-check/target
    entrypoint: ["/usr/share/dependency-check/bin/entrypoint.sh"]
    stdin_open: true
    tty: true
    environment:
      - REPO_NAME=${REPO_NAME}
      - LANGUAGE=${LANGUAGE}  
      - NVD_API_KEY=${NVD_API_KEY}

  grype-analyzer:
    platform: linux/amd64
    build: ./tools-scripts/grype
    working_dir: /
    volumes:
      - ./target:/root/target
    entrypoint: ["/root/entrypoint.sh"]
    environment:
      - REPO_NAME=${REPO_NAME}
      - LANGUAGE=${LANGUAGE}  
  semgrep-analyzer:
    platform: linux/amd64
    build: ./tools-scripts/semgrep
    working_dir: /
    volumes:
      - ./target:/root/target
    entrypoint: ["/root/entrypoint.sh"]
    environment:
      - REPO_NAME=${REPO_NAME}
      - LANGUAGE=${LANGUAGE} 

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  sonar-net:
    driver: bridge