version: "3.8"

services:
  codeql-analyzer:
    platform: linux/amd64
    build: ./tools-scripts/codeql
    volumes:
      - ./target:/root/target
      - ~/.m2:/root/.m2
    working_dir: /root
    entrypoint: ["/root/entrypoint.sh"]
    stdin_open: true
    tty: true
